"""Update schema

Revision ID: 128bfd04cc94
Revises: 3be9589831a0
Create Date: 2026-05-01 15:53:31.854236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128bfd04cc94'
down_revision = '3be9589831a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('reminder_minutes')
        batch_op.drop_column('repeat_type')

    # ### end Alembic commands ###
