"""Initial migration with new fields

Revision ID: 3be9589831a0
Revises: 
Create Date: 2026-05-01 12:34:12.526159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be9589831a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('font_family', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('default_reminder_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_reminder_minutes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('email_verified')
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('font_family')
        batch_op.drop_column('theme')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
